<main>
      <?php
      $tam=isset($_GET['quanly']) ? $_GET['quanly'] : "";
      if($tam=='dangky'){
        include("main/dangky.php");
      }
      if($tam=='dangnhap'){
        include('main/dangnhap.php');
      }
      if($tam=='giohang'){
        include('main/giohang.php');
      }
      if($tam=='tintuc'){
        include('main/tintuc.php');
      }
      if($tam=='taikhoan'){
        include('main/quanlytaikhoan/index.php');
        if(isset($_GET['query'])){
          if($_GET['query']=='choxacnhan'){
          include('main/quanlytaikhoan/choxacnhan.php');
          }
          if($_GET['query']=='danggiao'){
            include('main/quanlytaikhoan/danggiao.php');
          }
          if($_GET['query']=='hoanthanh'){
            include('main/quanlytaikhoan/hoanthanh.php');
          }
          if($_GET['query']=='taikhoan'){
            include('main/quanlytaikhoan/thongtincanhan.php');
          }
          if($_GET['query']=='tatca'){
            include('main/quanlytaikhoan/tatca.php');
          }
        }
        
        else{
          include('main/quanlytaikhoan/thongtincanhan.php');
        }
      }
      if($tam=='gioithieu'){
        include('main/gioithieu.php');
      }
      if($tam=='lienhe'){
        include('main/lienhe.php');
      }
      if($tam=='thanhtoan'){
        include('main/thanhtoan.php');
      }
      if(isset($_GET['danhmuc'])&&!isset($_GET['hieusanpham'])){
        include('main/danhmuc.php');
      }
      if(isset($_GET['hieusanpham'])&&isset($_GET['danhmuc'])){
        include('main/sanpham.php');
      }
      if(isset($_GET['sanpham'])){
        include('main/chitietsanpham.php');
      }
      if(isset($_GET['search_query'])){
        include('main/timkiemsanpham.php');
      }
      if(isset($_GET['timdon'])){
        include('main/quanlytaikhoan/index.php');
        include('main/quanlytaikhoan/timkiem.php');
      }
      if(isset($_GET['goiysp'])){
        include('main/goiysp.php');
      }
      // can sua
      if($tam==""&&!isset($_GET['danhmuc'])&&!isset($_GET['sanpham'])
      &&!isset($_GET['search_query'])&&!isset($_GET['goiysp'])&&!isset($_GET['timdon'])){
        include('main/index.php');
      }
      ?>
    </main>