<main>
      <?php
      $tam=isset($_GET['quanly']) ? $_GET['quanly'] : "";
      if($tam=='dangky'){
        include("main/dangky.php");
      }
      if($tam=='dangnhap'){
        include('main/dangnhap.php');
      }
      if($tam=='giohang'){
        include('main/giohang.php');
      }
      if($tam=='tintuc'){
        include('main/tintuc.php');
      }
      if(isset($_GET['danhmuc'])&&!isset($_GET['hieusanpham'])){
        include('main/danhmuc.php');
      }
      if(isset($_GET['hieusanpham'])&&isset($_GET['danhmuc'])){
        include('main/sanpham.php');
      }
      if(isset($_GET['sanpham'])){
        include('main/chitietsanpham.php');
      }
      if(isset($_GET['search_query'])){
        include('main/timkiemsanpham.php');
      }
      // can sua
      if($tam==""&&!isset($_GET['danhmuc'])&&!isset($_GET['sanpham'])&&!isset($_GET['search_query'])){
        include('main/index.php');
      }
      ?>
    </main>